In [1]:
import numpy as np

In [3]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [4]:
np.save('myarray', arr) # Saving the array

In [5]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.load('myarray.npy') # Load the array back

array([0, 1, 2, 3, 4])

In [8]:
arr2 = arr

In [9]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.savez('ziparray.npz',x=arr,y=arr2)

In [12]:
archive_array = np.load('ziparray.npz')

In [14]:
archive_array['x']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
archive_array['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
np.savetxt('mytxtarray.txt',arr,delimiter=',')

In [21]:
txtarr = np.loadtxt('mytxtarray.txt',delimiter=',')
txtarr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])